package uts.isd.model.dao;

import uts.isd.model.Account;

import java.sql.*;


public class AccountDAO {
    /**
     * Used to determine the type of a specified account.
     * Useful when trying to log the user in as either a Customer or Staff.
     *
     * @param email Email of Account
     * @param password Password of Account
     * @return Character representing the account type. Either 'C' or 'S'.
     * @throws SQLException When db access cannot be established.
     * @throws DAOException When account cannot be found.
     */
    public static char getAccountType(String email, String password) throws SQLException, DAOException {
        String accountTypeQuery =
                "SELECT ACCOUNT_TYPE FROM ACCOUNTS " +
                "WHERE EMAIL LIKE ? AND PASSWORD LIKE ?";

        PreparedStatement accountTypeSt = DAOUtils.prepareStatement(accountTypeQuery, false,
                email, password
        );

        ResultSet accountTypeRs = accountTypeSt.executeQuery();

        if (!accountTypeRs.next())
            throw new DAOException("No Account found. Incorrect Email or Password.");

        return accountTypeRs.getString("ACCOUNT_TYPE").charAt(0);
    }

    /**
     * Saves Account information to the database, creating a new row.
     * Returns the auto-generated primary key ID of the new account.
     * Use a try catch with DAOException to catch and display errors to the user.
     *
     * @param account The Account to save to the database.
     * @return The auto-generated ID of the new account.
     * @throws SQLException When db access cannot be established.
     * @throws DAOException When account creation fails.
     */
    public static int save(Account account) throws SQLException, DAOException {
        String query =
                "INSERT INTO ACCOUNTS (EMAIL, F_NAME, L_NAME, CONTACT_NUMBER, ACCOUNT_TYPE, PASSWORD, IS_ACTIVE) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement accountInsertSt = DAOUtils.prepareStatement(query, true,
                account.getEmail(),
                account.getFirstName(),
                account.getLastName(),
                account.getContactNumber(),
                String.valueOf(account.getAccountType()),
                account.getPassword(),
                account.isActive()
        );

        int rowsChanged = accountInsertSt.executeUpdate();
        if (rowsChanged == 0)
            throw new DAOException("Account creation failed. Please try again.");

        // Return Auto ID that was generated by SQL Server
        return DAOUtils.getGeneratedID(accountInsertSt);
    }
}
