DROP TABLE STAFF;
DROP TABLE CUSTOMERS;
DROP TABLE ORDER_LINE;
DROP TABLE ORDERS;
DROP TABLE PRODUCTS;
DROP TABLE PRODUCT_CATEGORIES;
DROP TABLE PAYMENT_INFORMATION;
DROP TABLE ACCOUNTS;

CREATE TABLE ACCOUNTS (
    "USER_ID" VARCHAR(50) NOT NULL,
    "USER_EMAIL" VARCHAR(50),
    "USER_F_NAME" VARCHAR(20),
    "USER_L_NAME" VARCHAR(20),
    "ACCOUNT_TYPE" VARCHAR(5),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE CUSTOMERS (
	"USER_ID" VARCHAR(50) NOT NULL,
	"ADDRESS_LINE_1" VARCHAR(50),
	"ADDRESS_LINE_2" VARCHAR(50),
	"SUBURB" VARCHAR(50),
	"STATE" VARCHAR(3),
	"POSTCODE" VARCHAR(4),
	"ANNONYMOUS" BOOLEAN,
	FOREIGN KEY ("USER_ID") REFERENCES ACCOUNTS ("USER_ID"),
	PRIMARY KEY ("USER_ID")
);

CREATE TABLE STAFF (
	"USER_ID" VARCHAR(50) NOT NULL,
	"PASSWORD" VARCHAR(50),
	"IS_ADMIN" BOOLEAN,
	FOREIGN KEY ("USER_ID") REFERENCES ACCOUNTS ("USER_ID"),
	PRIMARY KEY ("USER_ID")
);

CREATE TABLE PAYMENT_INFORMATION (
	"CARD_NUMBER" VARCHAR(50) NOT NULL,
	"USER_ID" VARCHAR(50) NOT NULL,
	"CVV_NUMBER" VARCHAR(50),
	"EXPIRY_MONTH" VARCHAR(50),
	"EXPIRY_YEAR" VARCHAR(50),
	PRIMARY KEY (CARD_NUMBER),
	FOREIGN KEY (USER_ID) REFERENCES ACCOUNTS (USER_ID)
);

CREATE TABLE ORDERS (
	"ORDER_ID" VARCHAR(50) NOT NULL, 
	"ORDER_DATE_TIME" VARCHAR(19),
	"ORDER_SHIPPING_ADDRESS" VARCHAR(50),
	"ORDER_TOTAL" DOUBLE,
	"USER_ID" VARCHAR(50),
	"TRACKING_ID" VARCHAR(30),
	"CARD_NUMBER" VARCHAR(50),
	PRIMARY KEY (ORDER_ID),
	FOREIGN KEY (USER_ID) REFERENCES ACCOUNTS (USER_ID),
	FOREIGN KEY (CARD_NUMBER) REFERENCES PAYMENT_INFORMATION (CARD_NUMBER)
);

CREATE TABLE PRODUCT_CATEGORIES (
	"CATEGORY_ID" VARCHAR(50) NOT NULL,
	"PRODUCT_CATEGORY" VARCHAR(255),
	"ARCHIVED" BOOLEAN,
	PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE PRODUCTS (
	"PRODUCT_ID" VARCHAR(50),
	"PRODUCT_NAME" VARCHAR(255),
	"STOCK" INTEGER,
	"PRODUCT_PRICE" DOUBLE,
	"CATEGORY_ID" VARCHAR(50),
	"PRODUCT_DESCRIPTION" VARCHAR(255),
	"ARCHIVED" VARCHAR(1),
    PRIMARY KEY (PRODUCT_ID),
	FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORIES (CATEGORY_ID)
);

CREATE TABLE ORDER_LINE (
	"ORDER_ID" VARCHAR(50), 
	"PRODUCT_ID" VARCHAR(50),
	"QUANTITY_ORDERED" INTEGER,
	"PRODUCT_PRICE" DOUBLE,
	FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
	FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID),
	PRIMARY KEY (ORDER_ID, PRODUCT_ID)
);